### ISSUE TITLE
Download link on Devot:ee is correct

### ISSUE THREAD

**Issue by objectivehtml** [mattfordham/Reedactor#1]
I had to copy/paste the URL, not a big deal but threw me for a loop at first. You should link up the Github master branch to the download link on Devotee to make it easier for people.

Really looking forward to trying this add-on, I was just tweeting about it last week that I really wanted a Redactor.js fieldtype for EE.

**Comment by mattfordham** [comment]
Oops. It is fixed. Thanks! :)
