### ISSUE TITLE
Tables tab

### ISSUE THREAD

**Issue by thkro** [mattfordham/Reedactor#2]
Hi,

This is a great plugin but how do I add the additional features like Tables or Text Alignment similar to the visiual structure on this page http://redactorjs.com/docs/examples/wym/

Thanks,
Thomas

**Comment by mattfordham** [comment]
Hey there. I haven't tested these particular configs, but in the reedactor.js file you put into the third party themes directory, you can modify the redactor.js jQuery code to add any config options you'd like.
