### ISSUE TITLE
Strip html on pasted content

### ISSUE THREAD

**Issue by kaspar-allenbach** [mattfordham/Reedactor#4]
Hi.

Is it possible to tell reedactor, to strip evey tag when copying text from a source to reedactor?

**Comment by mattfordham** [comment]
I'm not sure... check out the Redactor.js docs (http://redactorjs.com/docs/settings/). The "cleanup" setting may do it. You can tweak the settings in the js file that you dropped into the "themes/thirdparty" directory.
